import {intents} from "./intents/core";
import {responses} from "./responses/core";
import {BrainContext,BrainResult,Intent} from "./types";
import {synonyms} from "./language/synonyms";

export const normalize=(input:string)=>input.toLowerCase().normalize("NFKD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9\\s-]/g," ").replace(/\\s+/g," ").trim();
const variants=(value:string)=>{const n=normalize(value);const out=new Set([n]);for(const [key,items] of Object.entries(synonyms)){if(items.includes(n)||key===n)for(const item of items)out.add(normalize(item));}return [...out];};
const tokenSet=(text:string)=>new Set(normalize(text).split(" ").filter(Boolean));
function score(input:string,intent:Intent){const text=normalize(input);if(!text)return 0;let score=0;for(const p of intent.phrases)if(text===normalize(p))score+=.85;else if(text.includes(normalize(p)))score+=.58;for(const k of intent.keywords){const forms=variants(k);if(forms.some(v=>text.includes(v)))score+=.18;}const tokens=tokenSet(text);for(const k of intent.keywords)if(tokens.has(normalize(k)))score+=.08;return Math.min(.99,score+(intent.priority??0));}
export function think(input:string,context:BrainContext={}):BrainResult{const normalized=normalize(input);const ranked=intents.map(intent=>({intent,confidence:score(input,intent)})).sort((a,b)=>b.confidence-a.confidence);const best=ranked[0];if(!best||best.confidence<.30)return{intent:null,confidence:best?.confidence??0,response:responses.fallback[0],action:{type:"none"},normalized,alternatives:ranked.slice(0,3).filter(x=>x.confidence>0).map(x=>x.intent.id),needsClarification:false};const alternatives=ranked.filter(x=>x.confidence>0).slice(0,3);const ambiguous=alternatives.length>1&&best.confidence<.7&&best.confidence-alternatives[1].confidence<.12;if(ambiguous)return{intent:null,confidence:best.confidence,response:responses.unclear[0],action:{type:"none"},normalized,alternatives:alternatives.map(x=>x.intent.id),needsClarification:true};const response=(responses[best.intent.id]??responses.fallback)[0];return{intent:best.intent.id,confidence:best.confidence,response,action:best.intent.action??{type:"none"},normalized,alternatives:alternatives.map(x=>x.intent.id),needsClarification:false};}
