export type KnowledgeEntry={id:string;topic:string;questions:string[];keywords:string[];answer:string};
export const appKnowledge={name:"Crybots",scope:"Crybots app assistance",topics:["account","portfolio","deposits","withdrawals","transactions","trading","trade history","bots","marketplace","WorldScope","subscriptions","API keys","webhooks","security","device sessions","notifications","support","logs","settings","navigation","downloads","voice","admin"],rules:["Only answer within CryBots or directly related app topics.","Prefer verified facts sourced from the current CryBots frontend over generic assumptions.","Never invent balances, transactions, bot status, prices, subscription state, delivery outcomes, permissions, or account data.","Treat live account and market values as dynamic and query the connected CryBots bridge when available.","Use an app action only when the intent is sufficiently confident.","Ask for clarification instead of guessing when multiple intents are plausible.","Never claim that a navigation, subscription, transfer, withdrawal, bot action, webhook delivery, or security change succeeded unless the connected app confirms it."]} as const;
export const knowledge:KnowledgeEntry[]=[
{id:"what-is-crybots",topic:"general",questions:["what is crybots","what is crybots used for","tell me about crybots"],keywords:["crybots","platform","app"],answer:"Crybots is the app I am designed to help you navigate and understand. I can explain supported features and guide you to the right section."},
{id:"portfolio-purpose",topic:"portfolio",questions:["what is portfolio","what can i see in portfolio","what does portfolio show"],keywords:["portfolio","assets","holdings","balance"],answer:"Portfolio is where you view your Crybots assets and account holdings. I won't invent or guess your actual balance."},
{id:"deposit-purpose",topic:"deposits",questions:["what is a deposit","how does deposit work","where do deposits go"],keywords:["deposit","fund","top up"],answer:"A deposit is used to add funds to your Crybots account. I can take you to the Deposit section when you want to make one."},
{id:"withdraw-purpose",topic:"withdrawals",questions:["what is withdrawal","how does withdrawal work","how do withdrawals work"],keywords:["withdrawal","withdraw","cash out"],answer:"A withdrawal is used to move supported funds out of your Crybots account. I can take you to the Withdrawal section."},
{id:"bots-purpose",topic:"bots",questions:["what are bots","what do bots do","how do crybots bots work"],keywords:["bots","automation","automated"],answer:"Crybots bots are automated trading-related tools. My Bots is where supported created and active bots can be managed."},
{id:"api-purpose",topic:"api",questions:["what are api keys","why do i need an api key","what is an api key"],keywords:["api key","api keys","developer"],answer:"API keys are developer credentials used by supported integrations to access permitted Crybots data or actions. Keep them private and grant only the permissions you need."},
{id:"webhook-purpose",topic:"webhooks",questions:["what are webhooks","why use webhooks","what does a webhook do"],keywords:["webhook","webhooks","callback"],answer:"Webhooks let supported systems receive event notifications from Crybots. Webhook secrets and credentials should be treated as sensitive."},
{id:"security-purpose",topic:"security",questions:["how secure is crybots","what security does crybots have","how can i secure my account"],keywords:["security","2fa","authentication","password"],answer:"Crybots security features are managed from the Security area. Use strong credentials and available authentication protections, and never share security codes or private keys."},
{id:"voice-purpose",topic:"voice",questions:["what is voice mode","how does voice mode work","can i talk to crybots"],keywords:["voice","speaking","talk"],answer:"Voice mode lets you communicate with Crybots by speaking. Your speech is converted into text, then the Brain interprets the request and can return a supported response or action."},
{id:"brain-capabilities",topic:"general",questions:["what can you do","what commands do you understand","how can you help me"],keywords:["capabilities","commands","help me"],answer:"I can explain supported CryBots features, help with navigation, and check connected account data when the app makes it available. I cannot invent account values or claim an action succeeded without confirmation."},
{id:"brain-uncertainty",topic:"general",questions:["why did you ask me to clarify","do you guess answers"],keywords:["clarify","guess","understand me"],answer:"If a request could mean more than one thing, I may ask a follow-up instead of guessing. For balances, transactions, bot status, permissions, and other personal data, I should rely on actual available records."},
{id:"transaction-history-purpose",topic:"transactions",questions:["where is transaction history","how do i find a transaction","show me my payment records"],keywords:["transaction history","transaction records","payment history"],answer:"Transaction history helps you review recorded account movements and their statuses. Open a specific transaction’s details when you need more information; I should only report records returned by connected account data."},
{id:"trade-history-purpose",topic:"trading",questions:["where is trade history","how do i review old trades","where can i see completed trades"],keywords:["trade history","past trades","completed trades"],answer:"Trade History is for reviewing recorded trades. It differs from transaction history: transactions track account movements, while trade history focuses on trading activity. I should not guess your results or profit and loss."},
{id:"bot-performance-purpose",topic:"bots",questions:["how do i check bot performance","how can i tell if my bot is profitable","how do i review bot results"],keywords:["bot performance","bot results","bot profitability"],answer:"To understand a bot’s performance, review its available status, activity, and recorded trading results together. A bot being active does not by itself prove it is profitable. I should use actual returned records rather than estimate your results."},
{id:"bot-risk-purpose",topic:"bots",questions:["are trading bots risk free","can a bot guarantee profit","will my bot always make money"],keywords:["risk free","guaranteed profit","bot risk"],answer:"No trading bot can guarantee profit or eliminate market risk. Results can change with market conditions, strategy, execution, fees, and the asset being traded. Review actual records and understand the risks before relying on a bot."},
{id:"api-permissions-purpose",topic:"api",questions:["what api permissions should i give","should i give an api key all permissions","how do i keep api keys safe"],keywords:["api permissions","read permission","write permission","api key safety"],answer:"Use the minimum API permissions an integration needs. Read access is for permitted information; write access can allow changes or actions, depending on the permission group. Keep credentials private and revoke keys you no longer use."},
{id:"webhook-troubleshooting",topic:"webhooks",questions:["how do i troubleshoot a webhook","why is my webhook not working","what should i check when webhook delivery fails"],keywords:["webhook troubleshooting","webhook failed","delivery failed"],answer:"Check that the endpoint URL is correct and reachable, confirm the expected authentication or secret configuration, and inspect available delivery history or response details. Do not share webhook secrets publicly. I cannot confirm delivery succeeded unless the recorded result says so."},
{id:"security-code-purpose",topic:"security",questions:["what is my security code for","why does crybots ask for a security code","should i share my security code"],keywords:["security code","verification code","security confirmation"],answer:"A security code is an extra confirmation for protected actions when the app requests it. Never share it with another person or enter it into an untrusted page. If you did not initiate the action, stop and review your account security."},
{id:"device-sessions-purpose",topic:"security",questions:["where can i see logged in devices","what are device sessions","how do i review active sessions"],keywords:["device sessions","logged in devices","active sessions"],answer:"Device sessions help you review clients or devices associated with your account. Different app forms, such as web, PWA, or APK, may appear as separate session types. Review unfamiliar sessions and use the available security controls if something looks wrong."},
{id:"subscription-purpose",topic:"subscriptions",questions:["what is a subscription for","how do i manage my plan","what should i check before subscribing"],keywords:["subscription","plan","subscribe"],answer:"A subscription may unlock features or access according to the plan shown in the app. Check the plan details, price, and confirmation step before approving it. I should not claim you are subscribed or that payment occurred unless the app confirms it."},
{id:"worldscope-purpose",topic:"WorldScope",questions:["what is worldscope","what does worldscope do","how do i use worldscope"],keywords:["worldscope","world scope"],answer:"WorldScope is a dedicated area of the CryBots app. The exact information and controls available depend on the current page and your account access. Review its displayed sections; I should not invent live data or subscription status."},
{id:"notifications-purpose",topic:"notifications",questions:["where can i find alerts","how do i review old notifications","what are notifications for"],keywords:["alerts","notices","notification history"],answer:"Notifications collect available alerts and updates so you can review them later. If you are looking for a particular event, open Notifications and check the available details instead of assuming an alert was delivered."},
{id:"offline-purpose",topic:"general",questions:["can crybots work offline","what happens without internet","why is live data unavailable"],keywords:["offline","no internet","connection"],answer:"Some screens may remain available offline if already loaded or cached, but live account lookups, market updates, and server-backed actions generally need a connection. If live data cannot be retrieved, I should say so rather than make up a result."},
{id:"privacy-purpose",topic:"security",questions:["should i share my password","how do i protect my account information","is it safe to share private keys"],keywords:["password privacy","private key","sensitive information"],answer:"Keep passwords, security codes, API secrets, webhook secrets, and private keys confidential. Only enter credentials into the intended trusted app flow, and avoid sharing screenshots or messages that expose them."}
];
