export type KnowledgeEntry={id:string;topic:string;questions:string[];keywords:string[];answer:string};
export const appKnowledge={name:"Crybots",scope:"Crybots app assistance",topics:["account","portfolio","deposits","withdrawals","trading","bots","API keys","webhooks","security","settings","voice"],rules:["Only answer within Crybots or directly related app topics.","Never invent balances, transactions, bot status, prices, or account data.","Use an app action only when the intent is sufficiently confident.","Ask for clarification instead of guessing when multiple intents are plausible."]} as const;
export const knowledge:KnowledgeEntry[]=[
{id:"what-is-crybots",topic:"general",questions:["what is crybots","what is crybots used for","tell me about crybots"],keywords:["crybots","platform","app"],answer:"Crybots is the app I am designed to help you navigate and understand. I can explain supported features and guide you to the right section."},
{id:"portfolio-purpose",topic:"portfolio",questions:["what is portfolio","what can i see in portfolio","what does portfolio show"],keywords:["portfolio","assets","holdings","balance"],answer:"Portfolio is where you view your Crybots assets and account holdings. I won't invent or guess your actual balance."},
{id:"deposit-purpose",topic:"deposits",questions:["what is a deposit","how does deposit work","where do deposits go"],keywords:["deposit","fund","top up"],answer:"A deposit is used to add funds to your Crybots account. I can take you to the Deposit section when you want to make one."},
{id:"withdraw-purpose",topic:"withdrawals",questions:["what is withdrawal","how does withdrawal work","how do withdrawals work"],keywords:["withdrawal","withdraw","cash out"],answer:"A withdrawal is used to move supported funds out of your Crybots account. I can take you to the Withdrawal section."},
{id:"bots-purpose",topic:"bots",questions:["what are bots","what do bots do","how do crybots bots work"],keywords:["bots","automation","automated"],answer:"Crybots bots are automated trading-related tools. My Bots is where supported created and active bots can be managed."},
{id:"api-purpose",topic:"api",questions:["what are api keys","why do i need an api key","what is an api key"],keywords:["api key","api keys","developer"],answer:"API keys are developer credentials used by supported integrations to access permitted Crybots data or actions. Keep them private and grant only the permissions you need."},
{id:"webhook-purpose",topic:"webhooks",questions:["what are webhooks","why use webhooks","what does a webhook do"],keywords:["webhook","webhooks","callback"],answer:"Webhooks let supported systems receive event notifications from Crybots. Webhook secrets and credentials should be treated as sensitive."},
{id:"security-purpose",topic:"security",questions:["how secure is crybots","what security does crybots have","how can i secure my account"],keywords:["security","2fa","authentication","password"],answer:"Crybots security features are managed from the Security area. Use strong credentials and available authentication protections, and never share security codes or private keys."},
{id:"voice-purpose",topic:"voice",questions:["what is voice mode","how does voice mode work","can i talk to crybots"],keywords:["voice","speaking","talk"],answer:"Voice mode lets you communicate with Crybots by speaking. Your speech is converted into text, then the Brain interprets the request and can return a supported response or action."}
];
